set define off
set serveroutput on
whenever sqlerror exit sql.sqlcode

begin
  execute immediate q'[
    create table mio_players (
      player_id  number generated by default as identity primary key,
      nickname   varchar2(64) not null,
      created_at timestamp with time zone default systimestamp not null
    )
  ]';
exception when others then
  if sqlcode != -955 and sqlcode != -1408 then raise; end if;
end;
/

begin
  execute immediate q'[
    create table mio_game_sessions (
      session_id       varchar2(64) primary key
        references mio_demo_sessions(session_id) on delete cascade,
      player_id        number not null references mio_players(player_id),
      conversation_id  varchar2(256),
      challenge_type   varchar2(64) not null,
      current_state    varchar2(32) default 'hearing' not null,
      mio_message      clob,
      difficulty       number default 100 not null,
      turn_no          number default 1 not null,
      current_score    number default 0 not null,
      coins            number default 0 not null,
      combo_count      number default 0 not null,
      valid_turn_count number default 0 not null,
      total_turn_count number default 0 not null,
      choices_json     clob,
      started_at       timestamp with time zone default systimestamp not null,
      deadline_at      timestamp with time zone not null,
      turn_started_at  timestamp with time zone default systimestamp not null,
      ended_at         timestamp with time zone,
      time_limit_sec   number default 60 not null,
      final_score      number default 0 not null,
      rank_label       varchar2(16),
      title_label      varchar2(64),
      result_message   clob,
      cleared_flag     number(1) default 0 not null,
      status           varchar2(32) default 'playing' not null,
      created_at       timestamp with time zone default systimestamp not null
    )
  ]';
exception when others then
  if sqlcode != -955 and sqlcode != -1408 then raise; end if;
end;
/

begin
  execute immediate q'[
    create table mio_turns (
      turn_id             number generated by default as identity primary key,
      session_id          varchar2(64) not null
        references mio_game_sessions(session_id) on delete cascade,
      turn_no             number not null,
      challenge_type      varchar2(64) not null,
      current_state       varchar2(32),
      mio_message         clob,
      user_answer         clob,
      answer_type         varchar2(32),
      answer_vector       vector(1536, float32),
      embedding_model     varchar2(128) default 'cohere.embed-v4.0' not null,
      ideal_similarity    number,
      repeat_similarity   number,
      llm_quality_json    clob,
      quality_score       number default 0 not null,
      empathy_score       number default 0 not null,
      action_score        number default 0 not null,
      speed_score         number default 0 not null,
      turn_score          number default 0 not null,
      penalty_score       number default 0 not null,
      valid_flag          number(1) default 0 not null,
      score_detail_json   clob,
      difficulty_before   number,
      difficulty_after    number,
      elapsed_sec         number,
      next_mio_message    clob,
      response_json       clob,
      embedding_failed    number(1) default 0 not null,
      llm_eval_failed     number(1) default 0 not null,
      received_at         timestamp with time zone default systimestamp not null,
      created_at          timestamp with time zone default systimestamp not null,
      constraint mio_turns_session_turn_uk unique (session_id, turn_no)
    )
  ]';
exception when others then if sqlcode != -955 then raise; end if;
end;
/

begin
  execute immediate q'[
    create table mio_ideal_answers (
      ideal_id        number generated by default as identity primary key,
      challenge_type  varchar2(64) not null,
      turn_state      varchar2(32),
      ideal_text      clob not null,
      ideal_text_key  varchar2(64) not null unique,
      ideal_vector    vector(1536, float32),
      embedding_model varchar2(128) default 'cohere.embed-v4.0' not null,
      weight           number default 1 not null,
      created_at       timestamp with time zone default systimestamp not null
    )
  ]';
exception when others then if sqlcode != -955 then raise; end if;
end;
/

begin
  execute immediate q'[
    create table mio_score_events (
      event_id    number generated by default as identity primary key,
      session_id  varchar2(64) not null
        references mio_game_sessions(session_id) on delete cascade,
      turn_id     number references mio_turns(turn_id) on delete cascade,
      event_type  varchar2(64) not null,
      point_delta number not null,
      reason      varchar2(512),
      created_at  timestamp with time zone default systimestamp not null
    )
  ]';
exception when others then if sqlcode != -955 then raise; end if;
end;
/

begin
  execute immediate q'[
    create table mio_answer_templates (
      template_id     number generated by default as identity primary key,
      template_key    varchar2(64) not null unique,
      challenge_type  varchar2(64),
      template_text   varchar2(1000) not null,
      template_kind   varchar2(64),
      base_quality    number default 0 not null,
      is_active       char(1) default 'Y' not null,
      created_at      timestamp with time zone default systimestamp not null
    )
  ]';
exception when others then if sqlcode != -955 then raise; end if;
end;
/

begin
  execute immediate q'[
    create index mio_game_status_score_ix
      on mio_game_sessions(status, final_score, ended_at)
  ]';
exception when others then
  if sqlcode != -955 and sqlcode != -1408 then raise; end if;
end;
/

begin
  execute immediate q'[
    create index mio_turns_session_ix on mio_turns(session_id, turn_no)
  ]';
exception when others then
  if sqlcode != -955 and sqlcode != -1408 then raise; end if;
end;
/

commit;
prompt MIO Rescue schema is ready.
