#!/usr/bin/env python3
from __future__ import annotations

import argparse
import array
import json
import os
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Any

import oracledb

from export_mio_data import TABLES


SKIP_COLUMNS = {
    "MIO_DEMO_MESSAGES": {"MESSAGE_ID"},
    "MIO_DEMO_METRICS": {"METRIC_ID"},
}
IDENTITY_COLUMNS = {
    "MIO_PLAYERS": "PLAYER_ID",
    "MIO_TURNS": "TURN_ID",
    "MIO_IDEAL_ANSWERS": "IDEAL_ID",
    "MIO_SCORE_EVENTS": "EVENT_ID",
    "MIO_ANSWER_TEMPLATES": "TEMPLATE_ID",
}


def _db_value(value: Any) -> Any:
    if isinstance(value, dict) and "$datetime" in value:
        return datetime.fromisoformat(value["$datetime"])
    if isinstance(value, dict) and "$vector" in value:
        return array.array("f", value["$vector"])
    return value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    args = parser.parse_args()
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    wallet_zip = Path(os.environ["MIO_ADB_WALLET_ZIP"])
    with tempfile.TemporaryDirectory(prefix="mio-target-wallet-") as wallet_dir:
        with zipfile.ZipFile(wallet_zip) as archive:
            archive.extractall(wallet_dir)
        connection = oracledb.connect(
            user=os.getenv("MIO_ADB_USER", "admin"),
            password=os.environ["MIO_ADB_PASSWORD"],
            dsn=os.environ["MIO_ADB_DSN"],
            config_dir=wallet_dir,
            wallet_location=wallet_dir,
            wallet_password=os.environ["MIO_ADB_WALLET_PASSWORD"],
        )
        try:
            with connection.cursor() as cursor:
                for table in reversed(TABLES):
                    if table in payload["tables"]:
                        cursor.execute(f"delete from {table}")
                connection.commit()
                for table in TABLES:
                    table_data = payload["tables"].get(table)
                    if not table_data:
                        continue
                    skipped = SKIP_COLUMNS.get(table, set())
                    source_columns = table_data["columns"]
                    indexes = [index for index, name in enumerate(source_columns) if name not in skipped]
                    columns = [source_columns[index] for index in indexes]
                    binds = ",".join(f":{index + 1}" for index in range(len(columns)))
                    sql = f"insert into {table} ({','.join(columns)}) values ({binds})"
                    rows = [
                        tuple(_db_value(row[index]) for index in indexes)
                        for row in table_data["rows"]
                    ]
                    if rows:
                        cursor.executemany(sql, rows)
                    connection.commit()
                    print(f"imported {table}: {len(rows)} rows")
                for table, column in IDENTITY_COLUMNS.items():
                    if table in payload["tables"]:
                        cursor.execute(
                            f"alter table {table} modify {column} "
                            "generated by default as identity (start with limit value)"
                        )
                connection.commit()
        finally:
            connection.close()


if __name__ == "__main__":
    main()
