#!/usr/bin/env python3
from __future__ import annotations

import argparse
import array
import csv
import os
import re
import sys
import tempfile
import zipfile
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any

import oracledb

from export_mio_data import TABLES


SKIP_COLUMNS = {
    "MIO_DEMO_MESSAGES": {"MESSAGE_ID"},
    "MIO_DEMO_METRICS": {"METRIC_ID"},
}
IDENTITY_COLUMNS = {
    "MIO_PLAYERS": "PLAYER_ID",
    "MIO_TURNS": "TURN_ID",
    "MIO_IDEAL_ANSWERS": "IDEAL_ID",
    "MIO_SCORE_EVENTS": "EVENT_ID",
    "MIO_ANSWER_TEMPLATES": "TEMPLATE_ID",
}


def _timestamp(value: str) -> datetime:
    value = re.sub(r"(\.\d{6})\d+", r"\1", value)
    for pattern in (
        "%d-%b-%y %I.%M.%S.%f %p GMT",
        "%d-%b-%y %I.%M.%S %p GMT",
        "%Y-%m-%dT%H:%M:%S.%f%z",
        "%Y-%m-%dT%H:%M:%S%z",
    ):
        try:
            parsed = datetime.strptime(value.upper(), pattern)
            return parsed.replace(tzinfo=parsed.tzinfo or timezone.utc)
        except ValueError:
            continue
    return datetime.fromisoformat(value)


def _convert(value: str, data_type: str) -> Any:
    if value == "":
        return None
    if data_type == "VECTOR":
        import json

        return array.array("f", json.loads(value))
    if data_type == "NUMBER":
        return Decimal(value)
    if data_type.startswith("TIMESTAMP"):
        return _timestamp(value)
    return value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("directory", type=Path)
    args = parser.parse_args()
    csv.field_size_limit(sys.maxsize)
    wallet_zip = Path(os.environ["MIO_ADB_WALLET_ZIP"])
    with tempfile.TemporaryDirectory(prefix="mio-target-wallet-") as wallet_dir:
        with zipfile.ZipFile(wallet_zip) as archive:
            archive.extractall(wallet_dir)
        connection = oracledb.connect(
            user=os.getenv("MIO_ADB_USER", "admin"),
            password=os.environ["MIO_ADB_PASSWORD"],
            dsn=os.environ["MIO_ADB_DSN"],
            config_dir=wallet_dir,
            wallet_location=wallet_dir,
            wallet_password=os.environ["MIO_ADB_WALLET_PASSWORD"],
        )
        try:
            with connection.cursor() as cursor:
                present = {
                    table
                    for table in TABLES
                    if (args.directory / f"{table}_DATA_TABLE.csv").exists()
                }
                for table in reversed(TABLES):
                    if table in present:
                        cursor.execute(f"delete from {table}")
                connection.commit()

                for table in TABLES:
                    path = args.directory / f"{table}_DATA_TABLE.csv"
                    if not path.exists():
                        continue
                    cursor.execute(
                        "select column_name, data_type from user_tab_columns "
                        "where table_name = :table_name order by column_id",
                        table_name=table,
                    )
                    types = {name: data_type for name, data_type in cursor}
                    skipped = SKIP_COLUMNS.get(table, set())
                    count = 0
                    with path.open(newline="", encoding="utf-8") as handle:
                        reader = csv.DictReader(handle)
                        columns = [name for name in (reader.fieldnames or []) if name not in skipped]
                        binds = ",".join(f":{index + 1}" for index in range(len(columns)))
                        sql = f"insert into {table} ({','.join(columns)}) values ({binds})"
                        for row in reader:
                            values = tuple(_convert(row[name], types[name]) for name in columns)
                            cursor.execute(sql, values)
                            count += 1
                    connection.commit()
                    print(f"imported {table}: {count} rows")

                for table, column in IDENTITY_COLUMNS.items():
                    if table in present:
                        cursor.execute(
                            f"alter table {table} modify {column} "
                            "generated by default as identity (start with limit value)"
                        )
                connection.commit()
        finally:
            connection.close()


if __name__ == "__main__":
    main()
